language: node_js
node_js:
  - "stable"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bash coreutils grep make procps sed
  - sudo apt-get install -y closure-compiler curl git python xsltproc
  - sudo npm install jison -g
script: ./configure && make tests-all && make minify
